// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimbprMvc.Data;

#nullable disable

namespace SimbprMvc.Data.Migrations
{
    [DbContext(typeof(SimbprDbContext))]
    [Migration("20260318164349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimbprMvc.Models.Domain.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("")
                        .HasColumnName("comentarios");

                    b.Property<string>("Compania")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("")
                        .HasColumnName("compania");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Orden")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("orden");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.SimulacionBSN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amp")
                        .HasColumnType("float");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<int>("Etapas")
                        .HasColumnType("int");

                    b.Property<double>("Freq")
                        .HasColumnType("float");

                    b.Property<double>("Hp")
                        .HasColumnType("float");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("proyecto_id");

                    b.Property<double>("TempFondo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(90.0)
                        .HasColumnName("tempfondo");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<double>("Volt")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId")
                        .IsUnique();

                    b.ToTable("SimulacionBSN", (string)null);
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.SimulacionIPR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IprColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("#2563eb")
                        .HasColumnName("ipr_color");

                    b.Property<double>("JIndex")
                        .HasColumnType("float")
                        .HasColumnName("j_index");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("proyecto_id");

                    b.Property<double>("Pwf")
                        .HasColumnType("float");

                    b.Property<double>("Pws")
                        .HasColumnType("float");

                    b.Property<double>("Qb")
                        .HasColumnType("float");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId")
                        .IsUnique();

                    b.ToTable("SimulacionIPR", (string)null);
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.SimulacionProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Api")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(35.0)
                        .HasColumnName("api");

                    b.Property<double>("Bo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0)
                        .HasColumnName("bo");

                    b.Property<double>("Bsw")
                        .HasColumnType("float");

                    b.Property<double>("Gor")
                        .HasColumnType("float");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int")
                        .HasColumnName("proyecto_id");

                    b.Property<double>("Qt")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId")
                        .IsUnique();

                    b.ToTable("SimulacionProduccion", (string)null);
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.SimulacionBSN", b =>
                {
                    b.HasOne("SimbprMvc.Models.Domain.Proyecto", "Proyecto")
                        .WithOne("SimulacionBSN")
                        .HasForeignKey("SimbprMvc.Models.Domain.SimulacionBSN", "ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.SimulacionIPR", b =>
                {
                    b.HasOne("SimbprMvc.Models.Domain.Proyecto", "Proyecto")
                        .WithOne("SimulacionIPR")
                        .HasForeignKey("SimbprMvc.Models.Domain.SimulacionIPR", "ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.SimulacionProduccion", b =>
                {
                    b.HasOne("SimbprMvc.Models.Domain.Proyecto", "Proyecto")
                        .WithOne("SimulacionProduccion")
                        .HasForeignKey("SimbprMvc.Models.Domain.SimulacionProduccion", "ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SimbprMvc.Models.Domain.Proyecto", b =>
                {
                    b.Navigation("SimulacionBSN");

                    b.Navigation("SimulacionIPR");

                    b.Navigation("SimulacionProduccion");
                });
#pragma warning restore 612, 618
        }
    }
}
